package Volumenes;

import AreasPlanas.ACuadrado;
import AreasPlanas.APoligonoRegular;
import AreasPlanas.ATriangulo;

/**
 * @author Javier Fernandez Alvarado & Sergio Segura Vidal
 */
public class Escoger extends javax.swing.JFrame {

    /**
     * Creates new form VEscoger
     */
    
    public static double areaBase; 
    
    public Escoger() 
    {
        areaBase = 0;
        initComponents();
        setLocationRelativeTo(null);
    }
    
    
    public void seleccionarBase ()
    {
        if (jRTriangulo.isSelected())
        {
            ATriangulo aTri = new ATriangulo();
            aTri.pedirDatos();
            aTri.calcArea();
            areaBase = aTri.getArea();
        }
        else
        {
            if (jRCuadrado.isSelected())
            {
                ACuadrado aCua = new ACuadrado();
                aCua.pedirDatos();
                aCua.calcArea();
                areaBase = aCua.getArea();
            }
            else
            {
                if (jRPentagono.isSelected() || jRHexagono.isSelected())
                {
                    APoligonoRegular ap = new APoligonoRegular();
                    ap.pedirDatos();
                    ap.calcArea();
                    areaBase = ap.getArea();
                }
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bases = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRTriangulo = new javax.swing.JRadioButton();
        jRCuadrado = new javax.swing.JRadioButton();
        jRPentagono = new javax.swing.JRadioButton();
        jRHexagono = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("Seleccione la base de su figura");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/bases.png"))); // NOI18N

        bases.add(jRTriangulo);
        jRTriangulo.setSelected(true);

        bases.add(jRCuadrado);

        bases.add(jRPentagono);

        bases.add(jRHexagono);
        jRHexagono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRHexagonoActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1.setText("Seleccionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jRTriangulo)
                .addGap(95, 95, 95)
                .addComponent(jRCuadrado)
                .addGap(95, 95, 95)
                .addComponent(jRPentagono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRHexagono)
                .addGap(68, 68, 68))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jButton1)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRTriangulo)
                    .addComponent(jRCuadrado)
                    .addComponent(jRPentagono)
                    .addComponent(jRHexagono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRHexagonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRHexagonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRHexagonoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        seleccionarBase();
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Escoger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Escoger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Escoger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Escoger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Escoger().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bases;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRCuadrado;
    private javax.swing.JRadioButton jRHexagono;
    private javax.swing.JRadioButton jRPentagono;
    private javax.swing.JRadioButton jRTriangulo;
    // End of variables declaration//GEN-END:variables
}
