/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Matrices;

import javax.swing.JOptionPane;

/**
 *
 * @author Sergio Segura Vidal
 */
public class escogerTamanno extends javax.swing.JDialog {

    /**
     * Creates new form escogerTamanno
     */
    
    public static int numFilas;
    public static int numColumnas;
    
    public escogerTamanno(java.awt.Frame parent, boolean modal) 
    {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public void colocarTamanno(int num1,int num2)
    {
        numFilas = num1;
        numColumnas = num2;
        
        this.setVisible(false);
        
        Matriz mat = new Matriz();
    }
    
    public void setNombreMatriz (String nombre)
    {
        jLabel1.setText("Seleccione el tamaño de la matriz "+nombre);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jB4X4 = new javax.swing.JButton();
        jB3X4 = new javax.swing.JButton();
        jB2X4 = new javax.swing.JButton();
        jB4X3 = new javax.swing.JButton();
        jB3X3 = new javax.swing.JButton();
        jB2X3 = new javax.swing.JButton();
        jB4X2 = new javax.swing.JButton();
        jB3X2 = new javax.swing.JButton();
        jB2X2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Seleccione el tamaño de la matriz A");

        jB4X4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jB4X4.setText("4X4");
        jB4X4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB4X4ActionPerformed(evt);
            }
        });

        jB3X4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jB3X4.setText("3X4");
        jB3X4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB3X4ActionPerformed(evt);
            }
        });

        jB2X4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jB2X4.setText("2X4");
        jB2X4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB2X4ActionPerformed(evt);
            }
        });

        jB4X3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jB4X3.setText("4X3");
        jB4X3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB4X3ActionPerformed(evt);
            }
        });

        jB3X3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jB3X3.setText("3X3");
        jB3X3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB3X3ActionPerformed(evt);
            }
        });

        jB2X3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jB2X3.setText("2X3");
        jB2X3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB2X3ActionPerformed(evt);
            }
        });

        jB4X2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jB4X2.setText("4X2");
        jB4X2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB4X2ActionPerformed(evt);
            }
        });

        jB3X2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jB3X2.setText("3X2");
        jB3X2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB3X2ActionPerformed(evt);
            }
        });

        jB2X2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jB2X2.setText("2X2");
        jB2X2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB2X2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1.setText("Personalizado");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jB4X3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jB3X3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jB2X3))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jB4X2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jB3X2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jB2X2)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jB4X4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jB3X4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jB2X4))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB2X4)
                    .addComponent(jB3X4)
                    .addComponent(jB4X4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB2X3)
                    .addComponent(jB3X3)
                    .addComponent(jB4X3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB2X2)
                    .addComponent(jB3X2)
                    .addComponent(jB4X2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB4X4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB4X4ActionPerformed
        colocarTamanno(4, 4);
    }//GEN-LAST:event_jB4X4ActionPerformed

    private void jB3X4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB3X4ActionPerformed
        colocarTamanno(3, 4);
    }//GEN-LAST:event_jB3X4ActionPerformed

    private void jB2X4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB2X4ActionPerformed
        colocarTamanno(2, 4);
    }//GEN-LAST:event_jB2X4ActionPerformed

    private void jB4X3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB4X3ActionPerformed
        colocarTamanno(4, 3);
    }//GEN-LAST:event_jB4X3ActionPerformed

    private void jB3X3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB3X3ActionPerformed
        colocarTamanno(3, 3);
    }//GEN-LAST:event_jB3X3ActionPerformed

    private void jB2X3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB2X3ActionPerformed
        colocarTamanno(2, 3);
    }//GEN-LAST:event_jB2X3ActionPerformed

    private void jB4X2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB4X2ActionPerformed
        colocarTamanno(4, 2);
    }//GEN-LAST:event_jB4X2ActionPerformed

    private void jB3X2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB3X2ActionPerformed
        colocarTamanno(3, 2);
    }//GEN-LAST:event_jB3X2ActionPerformed

    private void jB2X2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB2X2ActionPerformed
        colocarTamanno(2, 2);
    }//GEN-LAST:event_jB2X2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        colocarTamanno(Integer.parseInt(JOptionPane.showInputDialog(null,
            "Digite el numero de filas")),
    Integer.parseInt(JOptionPane.showInputDialog(null,
        "Digite el numero de Columnas")));
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(escogerTamanno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(escogerTamanno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(escogerTamanno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(escogerTamanno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                escogerTamanno dialog = new escogerTamanno(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB2X2;
    private javax.swing.JButton jB2X3;
    private javax.swing.JButton jB2X4;
    private javax.swing.JButton jB3X2;
    private javax.swing.JButton jB3X3;
    private javax.swing.JButton jB3X4;
    private javax.swing.JButton jB4X2;
    private javax.swing.JButton jB4X3;
    private javax.swing.JButton jB4X4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
